### ISSUE TITLE
"[cpu monitor] failed to get pid of node" when relaunching killed nodes using roslaunch in terminal

### ISSUE THREAD

**Issue by cajuntai** [alspitz/cpu_monitor#12]
Hello, 
When testing the monitor.py, I've tried using rosrun commands on python scripts in the terminal to initialize nodes which had no problem in finding the process IDs of the nodes even when I've killed the nodes an re-rosrun the scripts. When I first used the roslaunch command in the terminal to initialize multiple nodes using their respective scripts, they were able to be added and their process IDs can be found. However, once I've killed the nodes (ctrl+c) and then re-roslaunch them, it gave me the error "[cpu monitor] failed to get pid of node" for all the nodes initialized by the launch file.

Out of curiosity, I put line 123 outside of the try-except statement, and it gave me the following error when i relaunch a previously killed node:

`Traceback (most recent call last):

  File "/usr/local/lib/python3.8/dist-packages/spyder_kernels/py3compat.py", line 356, in compat_exec
    exec(code, globals, locals)

  File "/home/cajun/catkin_ws/src/cpu_monitor/nodes/monitor.py", line 187, in <module>
    resp = ServerProxy(node_api).getPid('/rosnode') #Pid = Process ID (ID in system monitor)

  File "/usr/lib/python3.8/xmlrpc/client.py", line 1109, in __call__
    return self.__send(self.__name, args)

  File "/usr/lib/python3.8/xmlrpc/client.py", line 1450, in __request
    response = self.__transport.request(

  File "/usr/lib/python3.8/xmlrpc/client.py", line 1153, in request
    return self.single_request(host, handler, request_body, verbose)

  File "/usr/lib/python3.8/xmlrpc/client.py", line 1165, in single_request
    http_conn = self.send_request(host, handler, request_body, verbose)

  File "/usr/lib/python3.8/xmlrpc/client.py", line 1278, in send_request
    self.send_content(connection, request_body)

  File "/usr/lib/python3.8/xmlrpc/client.py", line 1308, in send_content
    connection.endheaders(request_body)

  File "/usr/lib/python3.8/http/client.py", line 1251, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)

  File "/usr/lib/python3.8/http/client.py", line 1011, in _send_output
    self.send(msg)

  File "/usr/lib/python3.8/http/client.py", line 951, in send
    self.connect()

  File "/usr/lib/python3.8/http/client.py", line 922, in connect
    self.sock = self._create_connection(

  File "/usr/lib/python3.8/socket.py", line 808, in create_connection
    raise err

  File "/usr/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)

ConnectionRefusedError: [Errno 111] Connection refused`

**Comment by alspitz** [comment]
@cajuntai Thanks for bringing this up. This is likely caused by `rosnode.get_api_uri` caching the results and getting stale data when a node with the same name reappeared. I've pushed a commit on master that should fix this by setting `skip_cache=True`. Let me know if it's still an issue.

**Comment by cajuntai** [comment]
Hi @alspitz, the issue is completely fixed now. Thanks!
